FONT_SIZE = 20
ANNOTATE = True

ALPHA_BOXES = .2
ALPHA_IMAGE = .4

PREDICTION_FILLED = False
TARGET_FILLED = True

PREDICTION_LABEL = 'numbers'
TARGET_LABEL = 'letters'

PREDICTION_COLOR = 'black'
TARGET_COLOR = 'cyclic'

MATCH_CMAP = 'Greys'
COST_CMAP = 'Oranges'
