from .Hungarian import Hungarian
from .Min import Min
from .ClosestTarget import ClosestTarget
from .ClosestPrediction import ClosestPrediction
from .SoftMin import SoftMin
from .BalancedSinkhorn import BalancedSinkhorn
from .UnbalancedSinkhorn import UnbalancedSinkhorn
from .BalancedPOT import BalancedPOT
from .UnbalancedPOT import UnbalancedPOT
from .WeightedSum import WeightedSum